# sudo: required
language: node_js

cache:
  directories:
    - src/client/node_modules
    - src/server/node_modules

node_js:
  - '14'

script:
  - cd src/client && npm install && npm run build
  - cd ../server && npm install && npm run build
