version: '3'
services:
    client:
        container_name: client
        build: .
        command: npm start
        volumes:
            - ./src:/usr/app/src
            - ./public:/usr/app/public
            - ./tsconfig.json:/usr/app/tsconfig.json
        ports:
            - '3000:3000'
